import type { Job, JobSource, UserProfile } from "@/lib/types";

export const mockSources: JobSource[] = [
  { id: "mock-source-1", name: "Mock UAE Feed", type: "mock", enabled: true, description: "Development data only" },
  { id: "mock-source-2", name: "Company Careers", type: "api", enabled: false, description: "Ready for future company integrations" },
];

export const mockProfile: UserProfile = {
  id: "profile-1",
  name: "Ayesha Rahman",
  targetRole: "Senior DevOps Engineer",
  experience: "5+ years",
  locationPreference: "Dubai, Abu Dhabi, Sharjah",
  skills: ["AWS", "Kubernetes", "Terraform", "Jenkins", "GitHub Actions", "ArgoCD", "Docker", "Observability"],
  cloudTechnologies: ["AWS", "GCP", "Azure", "Kubernetes"],
  certifications: ["AWS Solutions Architect", "CKA"],
  noticePeriod: "30 days",
  visaRequirement: "Open to UAE sponsorship",
  expectedSalary: "AED 25,000 - 35,000",
  currentLocation: "Dubai",
  relocationPreference: "Open to UAE relocation",
};

export const mockJobs: Job[] = [
  {
    id: "job-1",
    title: "Senior DevOps Engineer",
    company: "ABC Technologies",
    location: "Dubai, UAE",
    description:
      "Lead cloud operations and platform reliability at a fast-growing technology company in Dubai.",
    requirements: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Observability"],
    skills: ["AWS", "EKS", "Terraform", "Jenkins", "ArgoCD", "Helm", "Docker", "Prometheus"],
    experienceMin: 5,
    experienceMax: 8,
    salaryMin: 22000,
    salaryMax: 35000,
    salaryCurrency: "AED",
    postedAt: "2026-09-19T02:15:00.000Z",
    source: "Company Careers",
    sourceUrl: "https://example.com/jobs/senior-devops-engineer",
    applicationUrl: "https://example.com/apply/senior-devops-engineer",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    visaSponsorship: "Not specified",
    uaeExperience: "Not specified",
    certifications: ["AWS", "Terraform"],
    createdAt: "2026-09-19T00:00:00.000Z",
    updatedAt: "2026-09-19T00:00:00.000Z",
    matchPercentage: 91,
  },
  {
    id: "job-2",
    title: "Platform Engineer",
    company: "CloudNest UAE",
    location: "Abu Dhabi, UAE",
    description:
      "Build the internal cloud platform and improve delivery pipelines for mission-critical services.",
    requirements: ["Kubernetes", "AWS", "GitHub Actions", "SRE", "Linux"],
    skills: ["AWS", "Kubernetes", "GitHub Actions", "Terraform", "Docker", "Linux", "Helm"],
    experienceMin: 4,
    experienceMax: 7,
    salaryMin: 25000,
    salaryMax: 42000,
    salaryCurrency: "AED",
    postedAt: "2026-09-18T18:30:00.000Z",
    source: "LinkedIn",
    sourceUrl: "https://example.com/jobs/platform-engineer",
    applicationUrl: "https://example.com/apply/platform-engineer",
    employmentType: "Full-time",
    workArrangement: "On-site",
    visaSponsorship: "Visa sponsorship available",
    uaeExperience: "UAE experience preferred",
    certifications: ["Kubernetes", "AWS"],
    createdAt: "2026-09-18T18:00:00.000Z",
    updatedAt: "2026-09-18T18:00:00.000Z",
    matchPercentage: 88,
  },
  {
    id: "job-3",
    title: "SRE Engineer",
    company: "Nexa Systems",
    location: "Sharjah, UAE",
    description:
      "Own incident response, observability, and service reliability across production workloads.",
    requirements: ["Prometheus", "Grafana", "Kubernetes", "Linux", "AWS"],
    skills: ["AWS", "Kubernetes", "Prometheus", "Grafana", "Datadog", "Linux", "Bash"],
    experienceMin: 5,
    experienceMax: 9,
    salaryMin: 21000,
    salaryMax: 31000,
    salaryCurrency: "AED",
    postedAt: "2026-09-17T08:00:00.000Z",
    source: "Bayt",
    sourceUrl: "https://example.com/jobs/sre-engineer",
    applicationUrl: "https://example.com/apply/sre-engineer",
    employmentType: "Full-time",
    workArrangement: "Remote",
    visaSponsorship: "Not specified",
    uaeExperience: "Not specified",
    certifications: ["AWS", "Datadog"],
    createdAt: "2026-09-17T07:00:00.000Z",
    updatedAt: "2026-09-17T07:00:00.000Z",
    matchPercentage: 86,
  },
  {
    id: "job-4",
    title: "Cloud Security Engineer",
    company: "SecureCore Labs",
    location: "Dubai, UAE",
    description:
      "Design secure cloud deployments, scan for vulnerabilities, and improve compliance automation.",
    requirements: ["AWS", "DevSecOps", "Trivy", "Semgrep", "IAM"],
    skills: ["AWS", "IAM", "Terraform", "Trivy", "Semgrep", "Falco", "DevSecOps"],
    experienceMin: 5,
    experienceMax: 9,
    salaryMin: 26000,
    salaryMax: 43000,
    salaryCurrency: "AED",
    postedAt: "2026-09-19T08:45:00.000Z",
    source: "Company Careers",
    sourceUrl: "https://example.com/jobs/cloud-security-engineer",
    applicationUrl: "https://example.com/apply/cloud-security-engineer",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    visaSponsorship: "Immediate joiner",
    uaeExperience: "UAE experience required",
    certifications: ["AWS Security", "CISSP"],
    createdAt: "2026-09-19T06:00:00.000Z",
    updatedAt: "2026-09-19T06:00:00.000Z",
    matchPercentage: 82,
  },
  {
    id: "job-5",
    title: "Kubernetes Engineer",
    company: "Orbit Cloud",
    location: "Other UAE",
    description:
      "Manage production clusters, automate deployments, and improve service resilience across the platform.",
    requirements: ["Kubernetes", "EKS", "Helm", "Ingress", "RBAC"],
    skills: ["Kubernetes", "EKS", "Helm", "Ingress", "RBAC", "Docker", "Linux"],
    experienceMin: 4,
    experienceMax: 8,
    salaryMin: 20000,
    salaryMax: 33000,
    salaryCurrency: "AED",
    postedAt: "2026-09-15T12:00:00.000Z",
    source: "NaukriGulf",
    sourceUrl: "https://example.com/jobs/kubernetes-engineer",
    applicationUrl: "https://example.com/apply/kubernetes-engineer",
    employmentType: "Contract",
    workArrangement: "Remote",
    visaSponsorship: "Not specified",
    uaeExperience: "Not specified",
    certifications: ["CKA"],
    createdAt: "2026-09-15T11:00:00.000Z",
    updatedAt: "2026-09-15T11:00:00.000Z",
    matchPercentage: 90,
  },
  {
    id: "job-6",
    title: "Cloud Engineer",
    company: "EdgeOps",
    location: "Dubai, UAE",
    description:
      "Support large-scale cloud workloads and automate operational delivery in a multi-account AWS environment.",
    requirements: ["AWS", "Terraform", "CloudFormation", "CloudWatch", "Route53"],
    skills: ["AWS", "Terraform", "CloudWatch", "Route53", "IAM", "VPC", "Linux"],
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 19000,
    salaryMax: 29000,
    salaryCurrency: "AED",
    postedAt: "2026-09-12T11:00:00.000Z",
    source: "GulfTalent",
    sourceUrl: "https://example.com/jobs/cloud-engineer",
    applicationUrl: "https://example.com/apply/cloud-engineer",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    visaSponsorship: "Not specified",
    uaeExperience: "UAE experience preferred",
    certifications: ["AWS"],
    createdAt: "2026-09-12T10:00:00.000Z",
    updatedAt: "2026-09-12T10:00:00.000Z",
    matchPercentage: 84,
  },
  {
    id: "job-7",
    title: "DevSecOps Engineer",
    company: "Guardian Tech",
    location: "Abu Dhabi, UAE",
    description:
      "Integrate security tooling into CI/CD and platform workflows while supporting secure delivery at scale.",
    requirements: ["DevSecOps", "Trivy", "Semgrep", "GitLab CI", "AWS"],
    skills: ["AWS", "DevSecOps", "Trivy", "Semgrep", "GitLab CI", "SCA", "Falco"],
    experienceMin: 5,
    experienceMax: 8,
    salaryMin: 23000,
    salaryMax: 38000,
    salaryCurrency: "AED",
    postedAt: "2026-09-16T14:30:00.000Z",
    source: "Company Careers",
    sourceUrl: "https://example.com/jobs/devsecops-engineer",
    applicationUrl: "https://example.com/apply/devsecops-engineer",
    employmentType: "Full-time",
    workArrangement: "On-site",
    visaSponsorship: "Visa sponsorship available",
    uaeExperience: "UAE experience required",
    certifications: ["DevSecOps", "OWASP"],
    createdAt: "2026-09-16T13:00:00.000Z",
    updatedAt: "2026-09-16T13:00:00.000Z",
    matchPercentage: 89,
  },
  {
    id: "job-8",
    title: "Infrastructure Engineer",
    company: "Mosaic Digital",
    location: "Ras Al Khaimah, UAE",
    description:
      "Improve infrastructure automation across AWS and Azure by driving IaC standards and incident prevention.",
    requirements: ["Terraform", "AWS", "Azure", "Linux", "Networking"],
    skills: ["AWS", "Azure", "Terraform", "GitHub Actions", "Linux", "Docker", "Networking"],
    experienceMin: 5,
    experienceMax: 10,
    salaryMin: 24000,
    salaryMax: 36000,
    salaryCurrency: "AED",
    postedAt: "2026-09-19T03:20:00.000Z",
    source: "Indeed",
    sourceUrl: "https://example.com/jobs/infrastructure-engineer",
    applicationUrl: "https://example.com/apply/infrastructure-engineer",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    visaSponsorship: "Not specified",
    uaeExperience: "Not specified",
    certifications: ["Terraform"],
    createdAt: "2026-09-19T01:30:00.000Z",
    updatedAt: "2026-09-19T01:30:00.000Z",
    matchPercentage: 80,
  },
  {
    id: "job-9",
    title: "Cloud Reliability Engineer",
    company: "NorthStar Digital",
    location: "Dubai, UAE",
    description:
      "Drive reliability engineering practices for cloud services, incident management, and automation.",
    requirements: ["AWS", "Kubernetes", "Datadog", "Prometheus", "Python"],
    skills: ["AWS", "Kubernetes", "Python", "Datadog", "Prometheus", "Grafana", "Bash"],
    experienceMin: 6,
    experienceMax: 10,
    salaryMin: 27000,
    salaryMax: 44000,
    salaryCurrency: "AED",
    postedAt: "2026-09-14T17:15:00.000Z",
    source: "Company Careers",
    sourceUrl: "https://example.com/jobs/cloud-reliability-engineer",
    applicationUrl: "https://example.com/apply/cloud-reliability-engineer",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    visaSponsorship: "Not specified",
    uaeExperience: "UAE experience preferred",
    certifications: ["AWS", "Datadog"],
    createdAt: "2026-09-14T16:00:00.000Z",
    updatedAt: "2026-09-14T16:00:00.000Z",
    matchPercentage: 87,
  },
  {
    id: "job-10",
    title: "Production Engineer",
    company: "FutureScale",
    location: "Ajman, UAE",
    description:
      "Improve production readiness, service health, and release automation across a mixed cloud estate.",
    requirements: ["Linux", "Docker", "GitHub Actions", "Kubernetes", "Monitoring"],
    skills: ["Linux", "Docker", "GitHub Actions", "Kubernetes", "Prometheus", "Grafana", "Bash"],
    experienceMin: 4,
    experienceMax: 7,
    salaryMin: 18000,
    salaryMax: 28000,
    salaryCurrency: "AED",
    postedAt: "2026-09-18T13:00:00.000Z",
    source: "Bayt",
    sourceUrl: "https://example.com/jobs/production-engineer",
    applicationUrl: "https://example.com/apply/production-engineer",
    employmentType: "Permanent",
    workArrangement: "On-site",
    visaSponsorship: "Not specified",
    uaeExperience: "Not specified",
    certifications: ["Docker"],
    createdAt: "2026-09-18T12:00:00.000Z",
    updatedAt: "2026-09-18T12:00:00.000Z",
    matchPercentage: 79,
  },
];
